# Generated by Django 3.2.4 on 2021-06-20 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10)),
                ('age', models.IntegerField()),
                ('user_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('sentby', models.CharField(blank=True, choices=[('B', 'Bot'), ('U', 'User')], max_length=10)),
                ('sentat', models.DateTimeField(auto_now_add=True)),
                ('uname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedBotApp.myuser')),
            ],
        ),
    ]
