# Generated by Django 3.2.4 on 2021-06-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedBotApp', '0002_rename_uname_chatrecords_user_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrecords',
            name='sentby',
            field=models.CharField(blank=True, choices=[('Bot', 'Bot'), ('User', 'User')], max_length=10),
        ),
    ]
