# Generated by Django 3.2.4 on 2021-06-27 23:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedBotApp', '0005_alter_myuser_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='dob',
            field=models.DateField(default=datetime.date(2021, 6, 27)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=10),
        ),
        migrations.CreateModel(
            name='ImageRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='user_images')),
                ('bot_image', models.ImageField(blank=True, upload_to='bot_images')),
                ('purpose', models.CharField(blank=True, choices=[('Eye', 'Eye'), ('Exp', 'Exp')], max_length=3)),
                ('result', models.CharField(max_length=150)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('user_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedBotApp.myuser')),
            ],
        ),
    ]
