# Generated by Django 3.2.4 on 2021-07-04 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedBotApp', '0006_auto_20210627_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrecords',
            name='sentby',
            field=models.CharField(blank=True, choices=[('Bot', 'Bot'), ('User', 'User'), ('Dummy', 'Dummy')], max_length=10),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='dob',
            field=models.DateField(default=datetime.date(2021, 7, 4)),
        ),
    ]
