# Generated by Django 3.2.4 on 2021-07-06 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedBotApp', '0007_auto_20210704_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestChatRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_ref', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=1000)),
                ('sentby', models.CharField(blank=True, choices=[('Bot', 'Bot'), ('User', 'User'), ('Dummy', 'Dummy')], max_length=10)),
                ('sentat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='dob',
            field=models.DateField(default=datetime.date(2021, 7, 6)),
        ),
    ]
